#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Nov 01 14:40:16 CDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1.zip
