name = "SF5"
author = "Starplanet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a824cce3b4fadaa74667a4f6c5c11b37bea59fc0e45cb040887e8c373ae13fac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
