name = "SF5"
author = "Starplanet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfe7c0bc28592b014c2d8c83d8ae334837b0bc8d808dae553bb000ff97566836"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
