name = "SF5"
author = "Starplanet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc8fa95ae58325523bf52a135cf738df5d9a179da6441eda846039e76a698d9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
